[package]
name = "pieceboard"
version = "0.1.0"
edition = "2024"

[dependencies]
# pin ggez to a devel commit to get updated web-sys to make it compatible with iroh
ggez = { git = "https://github.com/ggez/ggez", rev = "9a4d240" }
sfn-tpn = "1.0"
tokio = "1.46.1"
